# Run Mr Coxall's Super Linter against code base #
##################################################

---
name: Mr Coxall's Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Mr Coxall's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository 🚦
        uses: actions/checkout@main

      - name: Run GitHub Super Linter 🚀
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PHP_BUILTIN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
